- hosts: dnac_servers
  vars_files:
    - credentials.yml
  gather_facts: no
  connection: local
  tasks:
    - name: Create Authentication and Policy Servers.
      cisco.dnac.ise_radius_integration_workflow_manager:
        dnac_host: "{{ dnac_host }}"
        dnac_port: "{{ dnac_port }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log: True
        dnac_log_level: "{{ dnac_log_level }}"
        dnac_log_append: True
        dnac_log_file_path: "{{ dnac_log_file_path }}"
        state: merged
        config_verify: True
        config:
        - authentication_policy_server:
            server_type: AAA # [ISE, AAA]
            server_ip_address: 172.23.241.245
            shared_secret: cisco
            protocol: RADIUS_TACACS # [TACACS, RADIUS, RADIUS_TACACS]
            encryption_scheme: KEYWRAP # KEYWRAP or RADSEC
            message_key: dnacisesolutions1234 # For KEYWRAP, must be 20 char long
            encryption_key: dnacsolutions123 # For KEYWRAP, must be 16 char long
            authentication_port: 1800
            accounting_port: 1700
            port: 40 # For TACACS
            retries: 3 # Range from 1 to 3
            timeout: 4 # Range from 2 to 20
            role: secondary
            # pxgrid_enabled: False # Avaliable for Cisco ISE only
            # use_dnac_cert_for_pxgrid: False
            # cisco_ise_dtos: # use this for creating the Cisco ISE Server
            # - user_name:
            #   password:
            #   fqdn:
            #   ip_address:
            #   subscriber_name:
            #   description:
            #   ssh_key:
            # external_cisco_ise_ip_addr_dtos:
            # - external_cisco_ise_ip_addresses:
            #   - external_ip_address:
            #   ise_type:

    - name: Create Authentication and Policy Servers.
      cisco.dnac.ise_radius_integration_workflow_manager:
        dnac_host: "{{ dnac_host }}"
        dnac_port: "{{ dnac_port }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log: True
        dnac_log_level: "{{ dnac_log_level }}"
        dnac_log_append: True
        dnac_log_file_path: "{{ dnac_log_file_path }}"
        state: deleted
        config_verify: True
        config:
        - authentication_policy_server:
            server_ip_address: 172.23.241.245
