name: main
on:
  pull_request_review:
    types: [submitted]
jobs:
  trigger-circleci:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-20.04
    steps:
      - run: echo -n "${GITHUB_REF}" | sed -r 's/^refs\///' | sed -r 's/merge/head/' > github_ref
      - name: Store ref for circleci trigger
        uses: actions/upload-artifact@v4
        with:
          name: github_ref-${{ github.run_id }}
          path: github_ref
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: reitermarkus/automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: rebase
          do-not-merge-labels: never-merge
#          pull-request: ${{ github.event.inputs.pull-request }}
          dry-run: false